import React, { useState, useEffect, useCallback } from 'react';
import {
  LayoutDashboard, BarChart2, RefreshCw,
  TrendingUp, TrendingDown, Minus, X, ChevronRight, Activity, History,
  Zap, Target, ArrowUpRight, ArrowDownRight,
} from 'lucide-react';
import { analyticsAPI } from '../services/api';
import StatCard from '../components/StatCard';
import PriceChart from '../components/PriceChart';
import CountChart from '../components/CountChart';
import UpdatesTable from '../components/UpdatesTable';
import RSIGauge from '../components/RSIGauge';
import InfoTooltip from '../components/InfoTooltip';
import HistoricalChart from './HistoricalChart';

// ── Coin registry ─────────────────────────────────────────────────────────────
const COINS = [
  { id: 'BTC-USD',  label: 'BTC',  name: 'Bitcoin',  color: '#f59e0b', desc: 'Original cryptocurrency' },
  { id: 'ETH-USD',  label: 'ETH',  name: 'Ethereum', color: '#8b5cf6', desc: 'Smart-contract platform' },
  { id: 'SOL-USD',  label: 'SOL',  name: 'Solana',   color: '#10b981', desc: 'High-speed blockchain' },
  { id: 'DOGE-USD', label: 'DOGE', name: 'Dogecoin', color: '#eab308', desc: 'Community-driven coin' },
];

const NAV = [
  { id: 'dashboard', label: 'Dashboard',       Icon: LayoutDashboard },
  { id: 'analytics', label: 'Analytics',       Icon: BarChart2 },
  { id: 'history',   label: 'Historical Data', Icon: History },
];

// ── Formatters ────────────────────────────────────────────────────────────────
const fmtPrice = (price, coinId) => {
  if (price == null) return '—';
  const d = coinId === 'DOGE-USD' ? 4 : 2;
  return `$${price.toLocaleString(undefined, { minimumFractionDigits: d, maximumFractionDigits: d })}`;
};
const fmtTime = (ts) => {
  if (!ts) return '—';
  try { return new Date(ts).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit' }); }
  catch { return '—'; }
};

// ── Whale Alert Banner ────────────────────────────────────────────────────────
const WhaleBanner = ({ alerts, onDismiss }) => {
  if (!alerts.length) return null;
  return (
    <div className="space-y-2 animate-fade-in">
      {alerts.map((a, i) => (
        <div key={i} className="flex items-center justify-between px-5 py-3 rounded-xl border border-blue-500/30 bg-blue-500/10 backdrop-blur-sm">
          <div className="flex items-center gap-3">
            <div className="w-7 h-7 rounded-lg bg-blue-500/15 border border-blue-500/30 flex items-center justify-center shrink-0">
              <Activity className="w-3.5 h-3.5 text-blue-400" />
            </div>
            <div>
              <span className="text-blue-300 font-semibold text-xs uppercase tracking-wide">Whale Activity Detected</span>
              <span className="text-slate-400 text-xs ml-2">— {a.coin}: {a.reason}</span>
            </div>
          </div>
          <button onClick={() => onDismiss(i)} className="text-slate-600 hover:text-slate-400 transition-colors ml-4 shrink-0">
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      ))}
      <p className="text-[11px] text-slate-600 px-1">
        Unusually high trade volume — large investors may be making significant moves.
      </p>
    </div>
  );
};

// ── Trading Signal Card ───────────────────────────────────────────────────────
const SignalCard = ({ signal, coin }) => {
  if (!signal) return null;
  const isBuy  = signal.signal === 'BUY';
  const isSell = signal.signal === 'SELL';
  const cfg = isBuy
    ? { bg: 'from-emerald-500/8', border: 'border-emerald-500/25', text: 'text-emerald-400', hint: 'Price is trending upward — algorithm suggests a buy position' }
    : isSell
    ? { bg: 'from-rose-500/8',    border: 'border-rose-500/25',    text: 'text-rose-400',    hint: 'Price is trending downward — algorithm suggests caution' }
    : { bg: 'from-amber-500/8',   border: 'border-amber-500/25',   text: 'text-amber-400',   hint: 'No clear trend — algorithm suggests waiting for confirmation' };

  return (
    <div className={`rounded-2xl border ${cfg.border} bg-gradient-to-r ${cfg.bg} to-transparent backdrop-blur-sm animate-fade-in`}>
      <div className="flex items-center gap-4 p-5">
        <div className="shrink-0 text-center w-20">
          <div className={`text-2xl font-black tracking-tight ${cfg.text}`}>{signal.signal}</div>
          <div className={`text-[10px] font-semibold uppercase tracking-widest mt-0.5 ${cfg.text} opacity-70`}>Signal</div>
        </div>
        <div className="w-px h-10 bg-slate-700/60 shrink-0" />
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className={`text-xs font-medium ${cfg.text}`}>{signal.reason}</span>
            <InfoTooltip text="This signal is generated by comparing short-term and long-term moving averages. It is not financial advice." />
          </div>
          <div className="flex flex-wrap gap-4 text-xs text-slate-500">
            <span>5-min avg: <span className="text-slate-300 font-medium">{fmtPrice(signal.ma5min, coin.id)}</span></span>
            <span>15-min avg: <span className="text-slate-300 font-medium">{fmtPrice(signal.ma15min, coin.id)}</span></span>
            <span>Now: <span className="font-semibold" style={{ color: coin.color }}>{fmtPrice(signal.currentPrice, coin.id)}</span></span>
          </div>
        </div>
        <div className="shrink-0 hidden sm:block">
          <span className={`text-[10px] font-semibold uppercase tracking-wider px-2.5 py-1 rounded-full border ${
            signal.confidence === 'High'   ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/25'
            : signal.confidence === 'Medium' ? 'bg-amber-500/10 text-amber-400 border-amber-500/25'
            : 'bg-slate-500/10 text-slate-400 border-slate-500/25'
          }`}>{signal.confidence} confidence</span>
        </div>
      </div>
      <div className="px-5 pb-3">
        <p className="text-[11px] text-slate-500">{cfg.hint}</p>
      </div>
    </div>
  );
};

// ── EMA Card ──────────────────────────────────────────────────────────────────
const EMACard = ({ latestRecord, coin }) => {
  if (!latestRecord?.ema || !latestRecord?.avgPrice) {
    return (
      <div className="rounded-2xl border border-slate-700/50 bg-slate-800/30 p-5 animate-fade-in stagger-2">
        <div className="flex items-center mb-3">
          <span className="text-[11px] font-semibold uppercase tracking-widest text-slate-500">EMA · 14-period</span>
          <InfoTooltip text="EMA (Exponential Moving Average) smooths out price fluctuations to show the real trend direction. If price is above EMA, momentum is upward." />
        </div>
        <div className="text-2xl font-bold text-slate-600 mb-1">—</div>
        <p className="text-[11px] text-slate-600">Warming up — collecting trend data</p>
      </div>
    );
  }

  const price = latestRecord.avgPrice;
  const ema   = latestRecord.ema;
  const diff  = price - ema;
  const pct   = ((Math.abs(diff) / ema) * 100).toFixed(2);
  const above = diff > 0;

  return (
    <div className="rounded-2xl border border-slate-700/50 bg-slate-800/30 backdrop-blur-sm p-5 hover:border-slate-600/50 transition-all duration-300 animate-fade-in stagger-2">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center">
          <span className="text-[11px] font-semibold uppercase tracking-widest text-slate-500">EMA · 14-period</span>
          <InfoTooltip text="EMA (Exponential Moving Average) smooths out price fluctuations to show the real trend direction. If price is above EMA, momentum is upward." />
        </div>
        <span className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-slate-700/60 text-slate-400 uppercase tracking-wider">Trend</span>
      </div>
      <div className="text-2xl font-bold text-white tabular-nums mb-3">{fmtPrice(ema, coin.id)}</div>
      <div className="mb-3">
        <div className="flex justify-between text-[11px] text-slate-500 mb-1.5">
          <span>Current price vs smoothed trend</span>
          <span className={`font-semibold ${above ? 'text-emerald-400' : 'text-rose-400'}`}>{above ? '+' : '-'}{pct}%</span>
        </div>
        <div className="h-1.5 rounded-full bg-slate-700 overflow-hidden">
          <div className={`h-full rounded-full transition-all duration-700 ${above ? 'bg-emerald-500' : 'bg-rose-500'}`}
            style={{ width: `${Math.min(100, Number(pct) * 10)}%` }} />
        </div>
      </div>
      <div className={`flex items-center gap-1.5 text-xs font-semibold ${above ? 'text-emerald-400' : 'text-rose-400'}`}>
        {above ? <TrendingUp className="w-3.5 h-3.5" /> : <TrendingDown className="w-3.5 h-3.5" />}
        Price is {above ? 'above' : 'below'} the trend line
      </div>
      <p className="text-[11px] text-slate-500 mt-1">
        {above ? 'Upward momentum — buyers are in control' : 'Downward pressure — sellers are in control'}
      </p>
    </div>
  );
};

// ── Key Insights Panel ────────────────────────────────────────────────────────
const KeyInsightsPanel = ({ highPrice, lowPrice, pctChange, volatility, coin }) => {
  const dec = coin.id === 'DOGE-USD' ? 4 : 2;
  const fmtP = (v) =>
    v != null ? `$${v.toLocaleString(undefined, { minimumFractionDigits: dec, maximumFractionDigits: dec })}` : '—';

  const volCfg =
    volatility === 'High'
      ? { color: 'text-rose-400',    border: 'border-rose-500/25',    bgFrom: 'from-rose-500/8',    iconBg: 'bg-rose-500/15 border-rose-500/25',    dot: 'bg-rose-400',    tip: 'Price is swinging a lot — expect big moves' }
      : volatility === 'Medium'
      ? { color: 'text-amber-400',   border: 'border-amber-500/25',   bgFrom: 'from-amber-500/8',   iconBg: 'bg-amber-500/15 border-amber-500/25',   dot: 'bg-amber-400',   tip: 'Moderate price movement — watch closely' }
      : { color: 'text-emerald-400', border: 'border-emerald-500/25', bgFrom: 'from-emerald-500/8', iconBg: 'bg-emerald-500/15 border-emerald-500/25', dot: 'bg-emerald-400', tip: 'Price is relatively stable right now' };

  const pctPos = pctChange != null && pctChange > 0;
  const pctNeg = pctChange != null && pctChange < 0;

  return (
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 animate-fade-in">

      {/* Highest Price */}
      <div className="rounded-2xl border border-emerald-500/20 bg-gradient-to-br from-emerald-500/8 to-transparent backdrop-blur-sm p-4 hover:border-emerald-500/35 hover:shadow-lg hover:shadow-emerald-500/5 transition-all duration-300 group">
        <div className="flex items-center gap-2 mb-3">
          <div className="w-7 h-7 rounded-xl bg-emerald-500/15 border border-emerald-500/25 flex items-center justify-center">
            <TrendingUp className="w-3.5 h-3.5 text-emerald-400" />
          </div>
          <span className="text-[10px] font-semibold uppercase tracking-widest text-slate-500">Highest</span>
        </div>
        <div className="text-[22px] font-bold text-white tabular-nums leading-none mb-1.5">{fmtP(highPrice)}</div>
        <p className="text-[10px] text-slate-500 leading-snug">Peak price in this session</p>
      </div>

      {/* Lowest Price */}
      <div className="rounded-2xl border border-rose-500/20 bg-gradient-to-br from-rose-500/8 to-transparent backdrop-blur-sm p-4 hover:border-rose-500/35 hover:shadow-lg hover:shadow-rose-500/5 transition-all duration-300 group">
        <div className="flex items-center gap-2 mb-3">
          <div className="w-7 h-7 rounded-xl bg-rose-500/15 border border-rose-500/25 flex items-center justify-center">
            <TrendingDown className="w-3.5 h-3.5 text-rose-400" />
          </div>
          <span className="text-[10px] font-semibold uppercase tracking-widest text-slate-500">Lowest</span>
        </div>
        <div className="text-[22px] font-bold text-white tabular-nums leading-none mb-1.5">{fmtP(lowPrice)}</div>
        <p className="text-[10px] text-slate-500 leading-snug">Floor price in this session</p>
      </div>

      {/* % Change */}
      <div className={`rounded-2xl border bg-gradient-to-br to-transparent backdrop-blur-sm p-4 transition-all duration-300 hover:shadow-lg ${
        pctPos ? 'border-emerald-500/20 from-emerald-500/6 hover:border-emerald-500/35 hover:shadow-emerald-500/5'
        : pctNeg ? 'border-rose-500/20 from-rose-500/6 hover:border-rose-500/35 hover:shadow-rose-500/5'
        : 'border-slate-700/50 from-slate-800/20 hover:border-slate-600/50'
      }`}>
        <div className="flex items-center gap-2 mb-3">
          <div className={`w-7 h-7 rounded-xl flex items-center justify-center border ${
            pctPos ? 'bg-emerald-500/15 border-emerald-500/25'
            : pctNeg ? 'bg-rose-500/15 border-rose-500/25'
            : 'bg-slate-700/40 border-slate-600/40'
          }`}>
            {pctPos
              ? <ArrowUpRight className="w-3.5 h-3.5 text-emerald-400" />
              : pctNeg
              ? <ArrowDownRight className="w-3.5 h-3.5 text-rose-400" />
              : <Minus className="w-3.5 h-3.5 text-slate-500" />}
          </div>
          <span className="text-[10px] font-semibold uppercase tracking-widest text-slate-500">% Change</span>
        </div>
        <div className={`text-[22px] font-bold tabular-nums leading-none mb-1.5 ${
          pctPos ? 'text-emerald-400' : pctNeg ? 'text-rose-400' : 'text-slate-400'
        }`}>
          {pctChange != null ? `${pctPos ? '+' : ''}${pctChange.toFixed(3)}%` : '—'}
        </div>
        <p className="text-[10px] text-slate-500 leading-snug">Price shift since window start</p>
      </div>

      {/* Volatility */}
      <div className={`rounded-2xl border bg-gradient-to-br ${volCfg.bgFrom} to-transparent backdrop-blur-sm p-4 hover:shadow-lg transition-all duration-300 ${volCfg.border}`}>
        <div className="flex items-center gap-2 mb-3">
          <div className={`w-7 h-7 rounded-xl flex items-center justify-center border ${volCfg.iconBg}`}>
            <Zap className={`w-3.5 h-3.5 ${volCfg.color}`} />
          </div>
          <span className="text-[10px] font-semibold uppercase tracking-widest text-slate-500">Volatility</span>
        </div>
        <div className={`text-[22px] font-bold leading-none mb-1.5 ${volCfg.color}`}>{volatility ?? '—'}</div>
        <p className="text-[10px] text-slate-500 leading-snug">{volCfg.tip}</p>
      </div>

    </div>
  );
};

// ── Market Summary Card ───────────────────────────────────────────────────────
const MarketSummaryCard = ({ trendDir, strength, volatility, coin }) => {
  const isBull = trendDir === 'Uptrend';
  const isBear = trendDir === 'Downtrend';

  const trendCfg = isBull
    ? { icon: <TrendingUp className="w-4 h-4" />,  color: 'text-emerald-400', sub: 'Price going up' }
    : isBear
    ? { icon: <TrendingDown className="w-4 h-4" />, color: 'text-rose-400',    sub: 'Price going down' }
    : { icon: <Minus className="w-4 h-4" />,        color: 'text-amber-400',   sub: 'No clear direction' };

  const strengthCfg =
    strength === 'Strong'   ? { color: 'text-emerald-400', sub: 'Clear, decisive movement' }
    : strength === 'Moderate' ? { color: 'text-amber-400',   sub: 'Momentum building up' }
    :                           { color: 'text-slate-400',   sub: 'Market is undecided' };

  const volColor =
    volatility === 'High'   ? 'text-rose-400'
    : volatility === 'Medium' ? 'text-amber-400'
    :                           'text-emerald-400';
  const volSub =
    volatility === 'High'   ? 'Big price swings — be careful'
    : volatility === 'Medium' ? 'Moderate swings — watch closely'
    :                           'Stable market — low risk';

  const reading =
    isBull && strength === 'Strong'   ? 'Price is climbing strongly. Buyers are in control right now.'
    : isBull                          ? 'Price is gradually moving up. Watch for confirmation.'
    : isBear && strength === 'Strong' ? 'Price is dropping fast. Sellers are dominant.'
    : isBear                          ? 'Price is drifting lower. Monitor for a reversal.'
    : volatility === 'High'           ? 'Price is choppy with no clear direction. Stay cautious.'
    :                                   'Price is stable. No strong trend either way.';

  return (
    <div className="rounded-2xl border border-slate-700/50 bg-slate-800/30 backdrop-blur-sm overflow-hidden animate-fade-in hover:border-slate-600/50 transition-all duration-300" style={{ borderLeft: `2px solid ${coin.color}40` }}>
      {/* Header */}
      <div className="flex items-center justify-between px-5 py-3.5 border-b border-slate-700/40">
        <div className="flex items-center gap-2.5">
          <div className="w-7 h-7 rounded-xl bg-slate-700/60 border border-slate-600/40 flex items-center justify-center">
            <Target className="w-3.5 h-3.5 text-slate-400" />
          </div>
          <span className="text-sm font-semibold text-slate-200">Market Summary</span>
          <InfoTooltip text="A plain-English breakdown of current market conditions based on recent price data. Not financial advice." />
        </div>
        <span className="text-[10px] text-slate-500 font-medium hidden sm:block">Based on recent price movement &amp; averages</span>
      </div>

      {/* Content */}
      <div className="flex flex-col sm:flex-row items-stretch divide-y sm:divide-y-0 sm:divide-x divide-slate-700/40">

        {/* Trend */}
        <div className="flex-1 px-5 py-4">
          <div className="text-[10px] font-semibold uppercase tracking-widest text-slate-500 mb-2">Trend Direction</div>
          <div className={`flex items-center gap-1.5 text-lg font-bold ${trendCfg.color} mb-1`}>
            {trendCfg.icon} {isBull ? 'Uptrend' : isBear ? 'Downtrend' : 'Sideways'}
          </div>
          <p className="text-[10px] text-slate-500">{trendCfg.sub}</p>
        </div>

        {/* Strength */}
        <div className="flex-1 px-5 py-4">
          <div className="text-[10px] font-semibold uppercase tracking-widest text-slate-500 mb-2">Trend Strength</div>
          <div className={`text-lg font-bold mb-1 ${strengthCfg.color}`}>{strength}</div>
          <p className="text-[10px] text-slate-500">{strengthCfg.sub}</p>
        </div>

        {/* Volatility */}
        <div className="flex-1 px-5 py-4">
          <div className="text-[10px] font-semibold uppercase tracking-widest text-slate-500 mb-2">Market Feel</div>
          <div className={`text-lg font-bold mb-1 ${volColor}`}>{volatility} Vol</div>
          <p className="text-[10px] text-slate-500">{volSub}</p>
        </div>

        {/* Plain reading */}
        <div className="px-5 py-4" style={{ flex: 2 }}>
          <div className="text-[10px] font-semibold uppercase tracking-widest text-slate-500 mb-2">What This Means</div>
          <p className="text-sm text-slate-300 font-medium leading-snug">{reading}</p>
          <p className="text-[10px] text-slate-600 mt-1.5">Not financial advice · updated every 5 seconds</p>
        </div>

      </div>
    </div>
  );
};

// ── Main Dashboard ────────────────────────────────────────────────────────────
const Dashboard = () => {
  const [selectedCoinId, setSelectedCoinId] = useState('BTC-USD');
  const [activeNav,      setActiveNav]      = useState('dashboard');
  const [summary,        setSummary]        = useState(null);
  const [recentData,     setRecentData]     = useState([]);
  const [hourlyData,     setHourlyData]     = useState([]);
  const [signal,         setSignal]         = useState(null);
  const [loading,        setLoading]        = useState(true);
  const [error,          setError]          = useState(null);
  const [lastUpdate,     setLastUpdate]     = useState(new Date());
  const [refreshing,     setRefreshing]     = useState(false);
  const [whaleAlerts,    setWhaleAlerts]    = useState([]);
  const [dismissed,      setDismissed]      = useState(new Set());

  const coin = COINS.find(c => c.id === selectedCoinId) || COINS[0];

  const fetchData = useCallback(async (sym = selectedCoinId, spin = false) => {
    if (spin) setRefreshing(true);
    try {
      const [sumR, recR, hrR, sigR] = await Promise.all([
        analyticsAPI.getSummary(sym),
        analyticsAPI.getRecent(sym, 30),
        analyticsAPI.getHourly(sym, 1),
        analyticsAPI.getTradingSignal(sym),
      ]);
      setSummary(sumR.data);
      const arr    = Array.isArray(recR.data) ? recR.data : [];
      const sorted = arr.reverse();
      setRecentData(sorted);
      setHourlyData(Array.isArray(hrR.data) ? hrR.data : []);
      setSignal(sigR.data);
      setError(null);
      setLastUpdate(new Date());

      const latest = sorted[sorted.length - 1];
      if (latest?.whaleAlert) {
        setWhaleAlerts(prev => {
          const exists = prev.some(a => a.coin === sym && a.reason === latest.whaleReason);
          if (exists) return prev;
          return [...prev.slice(-2), { coin: sym, reason: latest.whaleReason }];
        });
      }
    } catch {
      setError('Could not load market data. Ensure the backend is running on port 8080.');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [selectedCoinId]);

  useEffect(() => {
    setLoading(true);
    setSummary(null); setRecentData([]); setHourlyData([]); setSignal(null);
    fetchData(selectedCoinId);
  }, [selectedCoinId]);

  useEffect(() => {
    const id = setInterval(() => fetchData(selectedCoinId), 5000);
    return () => clearInterval(id);
  }, [selectedCoinId, fetchData]);

  const latestRecord = recentData[recentData.length - 1];
  const latestRsi    = latestRecord?.rsi;
  const priceTrend   = recentData.length >= 2
    ? ((recentData[recentData.length - 1]?.avgPrice - recentData[0]?.avgPrice) / recentData[0]?.avgPrice) * 100
    : null;
  const activeAlerts = whaleAlerts.filter((_, i) => !dismissed.has(i));

  // ── Derived insight values (computed from existing recentData) ────────────
  const priceArr  = recentData.filter(d => d?.avgPrice > 0).map(d => d.avgPrice);
  const highPrice = priceArr.length ? Math.max(...priceArr) : null;
  const lowPrice  = priceArr.length ? Math.min(...priceArr) : null;
  const meanPrice = priceArr.length ? priceArr.reduce((a, b) => a + b, 0) / priceArr.length : null;
  const stdDev    = meanPrice && priceArr.length > 1
    ? Math.sqrt(priceArr.reduce((sum, p) => sum + Math.pow(p - meanPrice, 2), 0) / priceArr.length)
    : 0;
  const volPct    = meanPrice ? (stdDev / meanPrice) * 100 : 0;
  const volatility = volPct > 0.15 ? 'High' : volPct > 0.04 ? 'Medium' : 'Low';
  const trendDir   = priceTrend == null ? 'Sideways' : priceTrend > 0.05 ? 'Uptrend' : priceTrend < -0.05 ? 'Downtrend' : 'Sideways';
  const strength   = priceTrend == null ? 'Weak' : Math.abs(priceTrend) < 0.1 ? 'Weak' : Math.abs(priceTrend) < 0.3 ? 'Moderate' : 'Strong';

  if (loading && !summary) {
    return (
      <div className="flex h-screen items-center justify-center bg-[#0a0f1a]">
        <div className="text-center space-y-3">
          <div className="w-12 h-12 rounded-2xl mx-auto flex items-center justify-center border"
            style={{ background: `${coin.color}15`, borderColor: `${coin.color}30` }}>
            <RefreshCw className="w-5 h-5 animate-spin" style={{ color: coin.color }} />
          </div>
          <p className="text-slate-400 text-sm">Loading market data…</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-screen bg-[#0a0f1a] overflow-hidden">

      {/* ── LEFT SIDEBAR ────────────────────────────────────────────────────── */}
      <aside className="w-[220px] shrink-0 flex flex-col border-r border-slate-800/70 bg-[#0c1220]">

        {/* Brand */}
        <div className="px-5 py-5 border-b border-slate-800/60">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg border border-slate-700/60 bg-slate-800 flex items-center justify-center">
              <BarChart2 className="w-3.5 h-3.5 text-slate-400" />
            </div>
            <div>
              <div className="text-sm font-bold text-white tracking-tight">CryptoMetrics</div>
              <div className="text-[10px] text-slate-600 uppercase tracking-widest">Real-Time Analytics</div>
            </div>
          </div>
        </div>

        {/* Coin selector */}
        <div className="px-3 pt-5 pb-3">
          <div className="text-[10px] font-semibold uppercase tracking-widest text-slate-600 px-2 mb-2">Select Coin</div>
          <div className="space-y-0.5">
            {COINS.map(c => {
              const active = c.id === selectedCoinId;
              return (
                <button key={c.id} id={`coin-${c.label.toLowerCase()}`}
                  onClick={() => setSelectedCoinId(c.id)}
                  className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm transition-all duration-200 group ${
                    active ? 'text-white' : 'text-slate-500 hover:text-slate-300 hover:bg-slate-800/40'
                  }`}
                  style={active ? { background: `linear-gradient(135deg, ${c.color}18, ${c.color}06)`, border: `1px solid ${c.color}30` } : {}}>
                  <span className={`w-2 h-2 rounded-full shrink-0 transition-all ${active ? '' : 'opacity-40 group-hover:opacity-70'}`}
                    style={{ background: c.color, boxShadow: active ? `0 0 6px ${c.color}60` : 'none' }} />
                  <div className="flex-1 text-left">
                    <div className={`text-sm font-semibold leading-none ${active ? 'text-white' : ''}`}>{c.label}</div>
                    <div className="text-[10px] text-slate-600 mt-0.5">{c.desc}</div>
                  </div>
                  {active && <ChevronRight className="w-3 h-3 shrink-0" style={{ color: c.color }} />}
                </button>
              );
            })}
          </div>
        </div>

        <div className="mx-5 border-t border-slate-800/60 my-1" />

        {/* Navigation */}
        <div className="px-3 pt-3 pb-3">
          <div className="text-[10px] font-semibold uppercase tracking-widest text-slate-600 px-2 mb-2">Navigation</div>
          <div className="space-y-0.5">
            {NAV.map(({ id, label, Icon }) => {
              const active = activeNav === id;
              return (
                <button key={id} onClick={() => setActiveNav(id)}
                  className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm transition-all duration-200 ${
                    active ? 'bg-slate-800/60 text-white border border-slate-700/50' : 'text-slate-500 hover:text-slate-300 hover:bg-slate-800/30'
                  }`}>
                  <Icon className={`w-4 h-4 shrink-0 ${active ? 'text-slate-300' : 'text-slate-600'}`} />
                  <span className="font-medium">{label}</span>
                  {id === 'history' && (
                    <span className="ml-auto text-[9px] px-1.5 py-0.5 rounded-md bg-slate-700/60 text-slate-500 font-semibold uppercase tracking-wider">New</span>
                  )}
                </button>
              );
            })}
          </div>
        </div>

        <div className="flex-1" />

        {/* Live indicator */}
        <div className="px-5 py-4 border-t border-slate-800/60">
          {error ? (
            <div className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-rose-500 shrink-0" />
              <span className="text-[11px] text-rose-400 font-medium">Disconnected</span>
            </div>
          ) : (
            <div className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full animate-pulse shrink-0" style={{ background: coin.color }} />
              <span className="text-[11px] text-slate-400 font-medium">Streaming live</span>
            </div>
          )}
          <p className="text-[10px] text-slate-600 mt-0.5">Updated {fmtTime(lastUpdate)}</p>
        </div>
      </aside>

      {/* ── MAIN CONTENT ────────────────────────────────────────────────────── */}
      <div className="flex-1 flex flex-col overflow-hidden">

        {/* Top bar */}
        <header className="flex items-center justify-between px-7 py-4 border-b border-slate-800/60 bg-[#0a0f1a]/80 backdrop-blur-sm shrink-0">
          <div>
            <div className="flex items-center gap-2.5">
              <div className="w-2 h-2 rounded-full" style={{ background: coin.color }} />
              <h1 className="text-base font-bold text-white tracking-tight">{coin.name}</h1>
              <span className="text-xs text-slate-500 font-medium">{coin.id}</span>
            </div>
            <p className="text-[11px] text-slate-600 mt-0.5">
              {activeNav === 'history'
                ? 'Query and explore historical price data collected by Flink'
                : 'Data streamed via Coinbase WebSocket · aggregated every 10 seconds'}
            </p>
          </div>
          <div className="flex items-center gap-3">
            {error && (
              <span className="text-xs text-rose-400 bg-rose-500/10 border border-rose-500/20 px-3 py-1.5 rounded-lg">
                Backend offline
              </span>
            )}
            {activeNav !== 'history' && (
              <button id="refresh-btn" onClick={() => fetchData(selectedCoinId, true)}
                className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-slate-200 transition-colors px-3 py-1.5 rounded-lg border border-slate-700/50 hover:border-slate-600/60 hover:bg-slate-800/40">
                <RefreshCw className={`w-3.5 h-3.5 ${refreshing ? 'animate-spin' : ''}`} />
                Refresh
              </button>
            )}
          </div>
        </header>

        {/* Scrollable content */}
        <div className="flex-1 overflow-y-auto px-7 py-6 space-y-5">

          {/* ── Historical Data view ── */}
          {activeNav === 'history' && (
            <HistoricalChart coin={coin} onBack={() => setActiveNav('dashboard')} />
          )}

          {/* ── Live Dashboard view ── */}
          {activeNav !== 'history' && (
            <>
              {/* Whale Alert */}
              <WhaleBanner
                alerts={activeAlerts}
                onDismiss={(i) => setDismissed(prev => new Set([...prev, i]))}
              />

              {/* Signal Card — hero */}
              <SignalCard signal={signal} coin={coin} />

              {/* Key Insights Panel — replaces raw StatCards */}
              <KeyInsightsPanel
                highPrice={highPrice}
                lowPrice={lowPrice}
                pctChange={priceTrend}
                volatility={volatility}
                coin={coin}
              />

              {/* RSI + EMA */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <RSIGauge rsi={latestRsi} coin={coin} />
                <EMACard latestRecord={latestRecord} coin={coin} />
              </div>

              {/* Price Trend + Trading Activity */}
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
                <PriceChart data={recentData} title="Price Trend" color={coin.color} coinId={coin.id} />
                <CountChart data={hourlyData} title="Trading Activity" color={coin.color} />
              </div>

              {/* Market Summary Card */}
              <MarketSummaryCard
                trendDir={trendDir}
                strength={strength}
                volatility={volatility}
                coin={coin}
              />

              {/* Last 5 Price Ticks — compact */}
              <UpdatesTable
                data={recentData.slice().reverse().slice(0, 5)}
                title="Last 5 Price Ticks"
                coin={coin}
              />
            </>
          )}

        </div>
      </div>
    </div>
  );
};

export default Dashboard;
