apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: coinbase
data:
  application.yml: |
    server:
      port: 8080

    spring:
      kafka:
        bootstrap-servers: kafka-service:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
          group-id: coinbase-analytics-group
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      data:
        mongodb:
          uri: mongodb://mongodb-service:27017/coinbase_analytics
