apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: coinbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: flink:1.18
          args: ["taskmanager"]
          ports:
            - containerPort: 6122
              name: rpc
          env:
            - name: JOB_MANAGER_RPC_ADDRESS
              value: "flink-jobmanager-service"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
