apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-service
  namespace: coinbase
spec:
  selector:
    app: flink
    component: jobmanager
  type: NodePort
  ports:
    - name: rpc
      port: 6123
      targetPort: 6123
    - name: web
      port: 8081
      targetPort: 8081
      nodePort: 30081  # Access Flink UI at Minikube-IP:30081
