apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: coinbase
spec:
  selector:
    app: kafka
  clusterIP: None  # Headless service
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
