apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: coinbase
spec:
  selector:
    app: mongodb
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
