apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: coinbase
spec:
  selector:
    app: zookeeper
  clusterIP: None  # Headless service
  ports:
    - port: 2181
      targetPort: 2181
      name: client
